# Generated by Django 2.1.5 on 2019-02-27 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('spellId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('higher_level', models.TextField()),
                ('range', models.CharField(max_length=240)),
                ('ritual', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=50)),
                ('concentration', models.CharField(max_length=50)),
                ('casting_time', models.CharField(max_length=255)),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='dnd_app.Character')),
            ],
        ),
    ]
