# Generated by Django 2.1.5 on 2019-02-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_app', '0002_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='higher_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
