# Generated by Django 2.1.5 on 2019-02-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('race', models.CharField(max_length=225)),
                ('characterClass', models.CharField(max_length=225)),
                ('intelligence', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('hitPoints', models.IntegerField(default=10)),
                ('ac', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('style', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('damage', models.TextField()),
                ('damageDetails', models.TextField(blank=True, null=True)),
                ('weaponId', models.AutoField(primary_key=True, serialize=False)),
                ('specialAffects', models.TextField(blank=True, null=True)),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='dnd_app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dnd_app.User'),
        ),
    ]
